{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "dee32135",
   "metadata": {},
   "source": [
    "<h1>Data Preprocessing of Inflation Data</h1>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b6e4e476",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib as plt\n",
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "id": "d620b333",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.model_selection import train_test_split, GridSearchCV\n",
    "from sklearn.linear_model import LinearRegression, Ridge\n",
    "from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "24df5c2e",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('exploredData')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "3d115180",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>7 Day Bobc</th>\n",
       "      <th>1 Month BoBC</th>\n",
       "      <th>CHN</th>\n",
       "      <th>EUR</th>\n",
       "      <th>GBP</th>\n",
       "      <th>USD</th>\n",
       "      <th>SDR</th>\n",
       "      <th>YEN</th>\n",
       "      <th>ZAR</th>\n",
       "      <th>CPI</th>\n",
       "      <th>CPIT</th>\n",
       "      <th>CPIXA</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2022-09-02</td>\n",
       "      <td>2.65</td>\n",
       "      <td>2.43</td>\n",
       "      <td>0.5340</td>\n",
       "      <td>0.0775</td>\n",
       "      <td>0.0670</td>\n",
       "      <td>0.0772</td>\n",
       "      <td>0.0595</td>\n",
       "      <td>10.84</td>\n",
       "      <td>1.3355</td>\n",
       "      <td>12.7</td>\n",
       "      <td>10.3</td>\n",
       "      <td>6.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2022-09-01</td>\n",
       "      <td>2.65</td>\n",
       "      <td>2.43</td>\n",
       "      <td>0.5359</td>\n",
       "      <td>0.0774</td>\n",
       "      <td>0.0670</td>\n",
       "      <td>0.0775</td>\n",
       "      <td>0.0596</td>\n",
       "      <td>10.80</td>\n",
       "      <td>1.3333</td>\n",
       "      <td>12.7</td>\n",
       "      <td>10.3</td>\n",
       "      <td>6.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2022-08-31</td>\n",
       "      <td>2.65</td>\n",
       "      <td>2.43</td>\n",
       "      <td>0.5395</td>\n",
       "      <td>0.0779</td>\n",
       "      <td>0.0669</td>\n",
       "      <td>0.0782</td>\n",
       "      <td>0.0599</td>\n",
       "      <td>10.82</td>\n",
       "      <td>1.3234</td>\n",
       "      <td>12.7</td>\n",
       "      <td>10.3</td>\n",
       "      <td>6.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2022-08-30</td>\n",
       "      <td>2.15</td>\n",
       "      <td>2.43</td>\n",
       "      <td>0.5420</td>\n",
       "      <td>0.0783</td>\n",
       "      <td>0.0669</td>\n",
       "      <td>0.0783</td>\n",
       "      <td>0.0601</td>\n",
       "      <td>10.85</td>\n",
       "      <td>1.3191</td>\n",
       "      <td>12.7</td>\n",
       "      <td>10.3</td>\n",
       "      <td>6.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2022-08-29</td>\n",
       "      <td>2.15</td>\n",
       "      <td>2.43</td>\n",
       "      <td>0.5405</td>\n",
       "      <td>0.0785</td>\n",
       "      <td>0.0669</td>\n",
       "      <td>0.0780</td>\n",
       "      <td>0.0600</td>\n",
       "      <td>10.83</td>\n",
       "      <td>1.3216</td>\n",
       "      <td>12.7</td>\n",
       "      <td>10.3</td>\n",
       "      <td>6.6</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         date  7 Day Bobc  1 Month BoBC     CHN     EUR     GBP     USD  \\\n",
       "0  2022-09-02        2.65          2.43  0.5340  0.0775  0.0670  0.0772   \n",
       "1  2022-09-01        2.65          2.43  0.5359  0.0774  0.0670  0.0775   \n",
       "2  2022-08-31        2.65          2.43  0.5395  0.0779  0.0669  0.0782   \n",
       "3  2022-08-30        2.15          2.43  0.5420  0.0783  0.0669  0.0783   \n",
       "4  2022-08-29        2.15          2.43  0.5405  0.0785  0.0669  0.0780   \n",
       "\n",
       "      SDR    YEN     ZAR   CPI  CPIT  CPIXA  \n",
       "0  0.0595  10.84  1.3355  12.7  10.3    6.6  \n",
       "1  0.0596  10.80  1.3333  12.7  10.3    6.6  \n",
       "2  0.0599  10.82  1.3234  12.7  10.3    6.6  \n",
       "3  0.0601  10.85  1.3191  12.7  10.3    6.6  \n",
       "4  0.0600  10.83  1.3216  12.7  10.3    6.6  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "8b38dcce",
   "metadata": {},
   "outputs": [],
   "source": [
    "df['date'] = pd.to_datetime(df['date'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9dbedf3f",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.set_index('date', inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "c6acc513",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>7 Day Bobc</th>\n",
       "      <th>1 Month BoBC</th>\n",
       "      <th>CHN</th>\n",
       "      <th>EUR</th>\n",
       "      <th>GBP</th>\n",
       "      <th>USD</th>\n",
       "      <th>SDR</th>\n",
       "      <th>YEN</th>\n",
       "      <th>ZAR</th>\n",
       "      <th>CPI</th>\n",
       "      <th>CPIT</th>\n",
       "      <th>CPIXA</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>date</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2022-09-02</th>\n",
       "      <td>2.65</td>\n",
       "      <td>2.43</td>\n",
       "      <td>0.5340</td>\n",
       "      <td>0.0775</td>\n",
       "      <td>0.0670</td>\n",
       "      <td>0.0772</td>\n",
       "      <td>0.0595</td>\n",
       "      <td>10.84</td>\n",
       "      <td>1.3355</td>\n",
       "      <td>12.7</td>\n",
       "      <td>10.3</td>\n",
       "      <td>6.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2022-09-01</th>\n",
       "      <td>2.65</td>\n",
       "      <td>2.43</td>\n",
       "      <td>0.5359</td>\n",
       "      <td>0.0774</td>\n",
       "      <td>0.0670</td>\n",
       "      <td>0.0775</td>\n",
       "      <td>0.0596</td>\n",
       "      <td>10.80</td>\n",
       "      <td>1.3333</td>\n",
       "      <td>12.7</td>\n",
       "      <td>10.3</td>\n",
       "      <td>6.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2022-08-31</th>\n",
       "      <td>2.65</td>\n",
       "      <td>2.43</td>\n",
       "      <td>0.5395</td>\n",
       "      <td>0.0779</td>\n",
       "      <td>0.0669</td>\n",
       "      <td>0.0782</td>\n",
       "      <td>0.0599</td>\n",
       "      <td>10.82</td>\n",
       "      <td>1.3234</td>\n",
       "      <td>12.7</td>\n",
       "      <td>10.3</td>\n",
       "      <td>6.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2022-08-30</th>\n",
       "      <td>2.15</td>\n",
       "      <td>2.43</td>\n",
       "      <td>0.5420</td>\n",
       "      <td>0.0783</td>\n",
       "      <td>0.0669</td>\n",
       "      <td>0.0783</td>\n",
       "      <td>0.0601</td>\n",
       "      <td>10.85</td>\n",
       "      <td>1.3191</td>\n",
       "      <td>12.7</td>\n",
       "      <td>10.3</td>\n",
       "      <td>6.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2022-08-29</th>\n",
       "      <td>2.15</td>\n",
       "      <td>2.43</td>\n",
       "      <td>0.5405</td>\n",
       "      <td>0.0785</td>\n",
       "      <td>0.0669</td>\n",
       "      <td>0.0780</td>\n",
       "      <td>0.0600</td>\n",
       "      <td>10.83</td>\n",
       "      <td>1.3216</td>\n",
       "      <td>12.7</td>\n",
       "      <td>10.3</td>\n",
       "      <td>6.6</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "            7 Day Bobc  1 Month BoBC     CHN     EUR     GBP     USD     SDR  \\\n",
       "date                                                                           \n",
       "2022-09-02        2.65          2.43  0.5340  0.0775  0.0670  0.0772  0.0595   \n",
       "2022-09-01        2.65          2.43  0.5359  0.0774  0.0670  0.0775  0.0596   \n",
       "2022-08-31        2.65          2.43  0.5395  0.0779  0.0669  0.0782  0.0599   \n",
       "2022-08-30        2.15          2.43  0.5420  0.0783  0.0669  0.0783  0.0601   \n",
       "2022-08-29        2.15          2.43  0.5405  0.0785  0.0669  0.0780  0.0600   \n",
       "\n",
       "              YEN     ZAR   CPI  CPIT  CPIXA  \n",
       "date                                          \n",
       "2022-09-02  10.84  1.3355  12.7  10.3    6.6  \n",
       "2022-09-01  10.80  1.3333  12.7  10.3    6.6  \n",
       "2022-08-31  10.82  1.3234  12.7  10.3    6.6  \n",
       "2022-08-30  10.85  1.3191  12.7  10.3    6.6  \n",
       "2022-08-29  10.83  1.3216  12.7  10.3    6.6  "
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "54ab93c1",
   "metadata": {},
   "source": [
    "<h3>Feature Engineering</h3>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d8f1bf26",
   "metadata": {},
   "source": [
    "The dataset already has a low dimensionality and so there is no need for dimensionality reduction. Also, the data is consistent and heterogenous. There is no feature engineering that will be done on this dataset."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8934f86e",
   "metadata": {},
   "source": [
    "In addition, all features are continuous, so there is no need to create any dummy variables. Instead, the data only needs to be scaled."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cd2ce7fc",
   "metadata": {},
   "source": [
    "<h4>Scaling the Data</h4>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e8b93a94",
   "metadata": {},
   "source": [
    "To scale the data, we use the StandardScaler object from sklearn preprocessing package. It scales the data by subtracting the mean from it and dividing by the standard deviation."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "f6d28265",
   "metadata": {},
   "outputs": [],
   "source": [
    "scaler = StandardScaler()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "7b5a2e10",
   "metadata": {},
   "outputs": [],
   "source": [
    "scale_df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns, index=df.index)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "id": "8c7156dd",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>7 Day Bobc</th>\n",
       "      <th>1 Month BoBC</th>\n",
       "      <th>CHN</th>\n",
       "      <th>EUR</th>\n",
       "      <th>GBP</th>\n",
       "      <th>USD</th>\n",
       "      <th>SDR</th>\n",
       "      <th>YEN</th>\n",
       "      <th>ZAR</th>\n",
       "      <th>CPI</th>\n",
       "      <th>CPIT</th>\n",
       "      <th>CPIXA</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>date</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2022-09-02</th>\n",
       "      <td>-0.407504</td>\n",
       "      <td>10.675415</td>\n",
       "      <td>0.971495</td>\n",
       "      <td>-1.157787</td>\n",
       "      <td>-0.925579</td>\n",
       "      <td>-1.524403</td>\n",
       "      <td>-1.019696</td>\n",
       "      <td>-0.362137</td>\n",
       "      <td>0.884880</td>\n",
       "      <td>1.979911</td>\n",
       "      <td>1.543426</td>\n",
       "      <td>0.278027</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2022-09-01</th>\n",
       "      <td>-0.407504</td>\n",
       "      <td>10.675415</td>\n",
       "      <td>0.977786</td>\n",
       "      <td>-1.166694</td>\n",
       "      <td>-0.925579</td>\n",
       "      <td>-1.511922</td>\n",
       "      <td>-1.013919</td>\n",
       "      <td>-0.386265</td>\n",
       "      <td>0.865676</td>\n",
       "      <td>1.979911</td>\n",
       "      <td>1.543426</td>\n",
       "      <td>0.278027</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2022-08-31</th>\n",
       "      <td>-0.407504</td>\n",
       "      <td>10.675415</td>\n",
       "      <td>0.989705</td>\n",
       "      <td>-1.122159</td>\n",
       "      <td>-0.935353</td>\n",
       "      <td>-1.482802</td>\n",
       "      <td>-0.996590</td>\n",
       "      <td>-0.374201</td>\n",
       "      <td>0.779260</td>\n",
       "      <td>1.979911</td>\n",
       "      <td>1.543426</td>\n",
       "      <td>0.278027</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2022-08-30</th>\n",
       "      <td>-0.539386</td>\n",
       "      <td>10.675415</td>\n",
       "      <td>0.997982</td>\n",
       "      <td>-1.086531</td>\n",
       "      <td>-0.935353</td>\n",
       "      <td>-1.478641</td>\n",
       "      <td>-0.985037</td>\n",
       "      <td>-0.356105</td>\n",
       "      <td>0.741726</td>\n",
       "      <td>1.979911</td>\n",
       "      <td>1.543426</td>\n",
       "      <td>0.278027</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2022-08-29</th>\n",
       "      <td>-0.539386</td>\n",
       "      <td>10.675415</td>\n",
       "      <td>0.993016</td>\n",
       "      <td>-1.068717</td>\n",
       "      <td>-0.935353</td>\n",
       "      <td>-1.491122</td>\n",
       "      <td>-0.990813</td>\n",
       "      <td>-0.368169</td>\n",
       "      <td>0.763548</td>\n",
       "      <td>1.979911</td>\n",
       "      <td>1.543426</td>\n",
       "      <td>0.278027</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2008-05-01</th>\n",
       "      <td>2.048134</td>\n",
       "      <td>-0.093949</td>\n",
       "      <td>-0.796522</td>\n",
       "      <td>0.910932</td>\n",
       "      <td>1.295454</td>\n",
       "      <td>1.110868</td>\n",
       "      <td>0.802131</td>\n",
       "      <td>1.017667</td>\n",
       "      <td>-0.508224</td>\n",
       "      <td>1.805058</td>\n",
       "      <td>1.771813</td>\n",
       "      <td>1.064576</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2008-06-01</th>\n",
       "      <td>2.048134</td>\n",
       "      <td>-0.093949</td>\n",
       "      <td>-0.796522</td>\n",
       "      <td>0.910932</td>\n",
       "      <td>1.295454</td>\n",
       "      <td>1.110868</td>\n",
       "      <td>0.802131</td>\n",
       "      <td>1.017667</td>\n",
       "      <td>-0.508224</td>\n",
       "      <td>2.504472</td>\n",
       "      <td>2.261215</td>\n",
       "      <td>1.284810</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2008-07-01</th>\n",
       "      <td>2.048134</td>\n",
       "      <td>-0.093949</td>\n",
       "      <td>-0.796522</td>\n",
       "      <td>0.910932</td>\n",
       "      <td>1.295454</td>\n",
       "      <td>1.110868</td>\n",
       "      <td>0.802131</td>\n",
       "      <td>1.017667</td>\n",
       "      <td>-0.508224</td>\n",
       "      <td>2.650183</td>\n",
       "      <td>2.326468</td>\n",
       "      <td>1.693816</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2008-03-01</th>\n",
       "      <td>2.048134</td>\n",
       "      <td>-0.093949</td>\n",
       "      <td>-0.796522</td>\n",
       "      <td>0.910932</td>\n",
       "      <td>1.295454</td>\n",
       "      <td>1.110868</td>\n",
       "      <td>0.802131</td>\n",
       "      <td>1.017667</td>\n",
       "      <td>-0.508224</td>\n",
       "      <td>1.134786</td>\n",
       "      <td>1.347665</td>\n",
       "      <td>1.001652</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2008-01-01</th>\n",
       "      <td>2.048134</td>\n",
       "      <td>-0.093949</td>\n",
       "      <td>-0.796522</td>\n",
       "      <td>0.910932</td>\n",
       "      <td>1.295454</td>\n",
       "      <td>1.110868</td>\n",
       "      <td>0.802131</td>\n",
       "      <td>1.017667</td>\n",
       "      <td>-0.508224</td>\n",
       "      <td>0.726794</td>\n",
       "      <td>0.760383</td>\n",
       "      <td>0.466799</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>3771 rows × 12 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "            7 Day Bobc  1 Month BoBC       CHN       EUR       GBP       USD  \\\n",
       "date                                                                           \n",
       "2022-09-02   -0.407504     10.675415  0.971495 -1.157787 -0.925579 -1.524403   \n",
       "2022-09-01   -0.407504     10.675415  0.977786 -1.166694 -0.925579 -1.511922   \n",
       "2022-08-31   -0.407504     10.675415  0.989705 -1.122159 -0.935353 -1.482802   \n",
       "2022-08-30   -0.539386     10.675415  0.997982 -1.086531 -0.935353 -1.478641   \n",
       "2022-08-29   -0.539386     10.675415  0.993016 -1.068717 -0.935353 -1.491122   \n",
       "...                ...           ...       ...       ...       ...       ...   \n",
       "2008-05-01    2.048134     -0.093949 -0.796522  0.910932  1.295454  1.110868   \n",
       "2008-06-01    2.048134     -0.093949 -0.796522  0.910932  1.295454  1.110868   \n",
       "2008-07-01    2.048134     -0.093949 -0.796522  0.910932  1.295454  1.110868   \n",
       "2008-03-01    2.048134     -0.093949 -0.796522  0.910932  1.295454  1.110868   \n",
       "2008-01-01    2.048134     -0.093949 -0.796522  0.910932  1.295454  1.110868   \n",
       "\n",
       "                 SDR       YEN       ZAR       CPI      CPIT     CPIXA  \n",
       "date                                                                    \n",
       "2022-09-02 -1.019696 -0.362137  0.884880  1.979911  1.543426  0.278027  \n",
       "2022-09-01 -1.013919 -0.386265  0.865676  1.979911  1.543426  0.278027  \n",
       "2022-08-31 -0.996590 -0.374201  0.779260  1.979911  1.543426  0.278027  \n",
       "2022-08-30 -0.985037 -0.356105  0.741726  1.979911  1.543426  0.278027  \n",
       "2022-08-29 -0.990813 -0.368169  0.763548  1.979911  1.543426  0.278027  \n",
       "...              ...       ...       ...       ...       ...       ...  \n",
       "2008-05-01  0.802131  1.017667 -0.508224  1.805058  1.771813  1.064576  \n",
       "2008-06-01  0.802131  1.017667 -0.508224  2.504472  2.261215  1.284810  \n",
       "2008-07-01  0.802131  1.017667 -0.508224  2.650183  2.326468  1.693816  \n",
       "2008-03-01  0.802131  1.017667 -0.508224  1.134786  1.347665  1.001652  \n",
       "2008-01-01  0.802131  1.017667 -0.508224  0.726794  0.760383  0.466799  \n",
       "\n",
       "[3771 rows x 12 columns]"
      ]
     },
     "execution_count": 56,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "scale_df"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "94b81265",
   "metadata": {},
   "source": [
    "<h4>Breaking data into Training and Test sets</h4>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6d85dd51",
   "metadata": {},
   "source": [
    "It is important to note that cpi, cpit, and cpixa are all measures of inflation rate even though cpi is the most common one. They will all be treated as target variables to see if the prediction model will be able to perform better predicting one of them than the others."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e65b227b",
   "metadata": {},
   "source": [
    "The data shall now be separated into test and training sets. Sklearn has a package that provides this functionality. See below:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "id": "d57a9a46",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Firstly splitting the target variable(y) from the predictor variables(X)\n",
    "X = scale_df.drop(columns=['CPI', 'CPIT', 'CPIXA'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "id": "18953315",
   "metadata": {},
   "outputs": [],
   "source": [
    "y = scale_df['CPI']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "9ba9a185",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "557d31ad",
   "metadata": {},
   "source": [
    "Sometimes it is possible to use multiple target variables and this option will be explored farther on."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7e0c1eda",
   "metadata": {},
   "source": [
    "Now, a linear regression algorithm from sklearn will be used as the baseline."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "id": "85154ec3",
   "metadata": {},
   "outputs": [],
   "source": [
    "lm = LinearRegression()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "id": "87e2e43d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "LinearRegression()"
      ]
     },
     "execution_count": 61,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "lm.fit(X_train,y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "id": "102b4f1c",
   "metadata": {},
   "outputs": [],
   "source": [
    "ypred = lm.predict(X_test) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "id": "75f1e6a6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "R2 Score: 0.6187787845654473\n",
      "Mean Squared Error: 0.3939166004809056\n",
      "Mean Absolute Error: 0.46519847896278915\n"
     ]
    }
   ],
   "source": [
    "print('R2 Score: ' + str(r2_score(y_test, ypred)))\n",
    "print('Mean Squared Error: ' + str(mean_squared_error(y_test, ypred)))\n",
    "print('Mean Absolute Error: ' + str(mean_absolute_error(y_test, ypred)))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9d7e2285",
   "metadata": {},
   "source": [
    "The linear regression model was able to achieve an R_squared value of 0.6188 without any hyperparameter tuning. Also, this may not be the most accurate result since there could have been some sampling bias. To solve this, a gridsearch object will be used to do some parameter tuning and also to perform cross-validation, which will use each part of the dataset as the test set and get the mean of the results. We will use five folds."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "id": "89119fb7",
   "metadata": {},
   "outputs": [],
   "source": [
    "lm2=LinearRegression()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "id": "8f76cb2d",
   "metadata": {},
   "outputs": [],
   "source": [
    "grid_search = GridSearchCV(lm2, param_grid={'copy_X': [True,False], 'fit_intercept': [True, False]},  cv=5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "id": "2dc07e16",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "GridSearchCV(cv=5, estimator=LinearRegression(),\n",
       "             param_grid={'copy_X': [True, False],\n",
       "                         'fit_intercept': [True, False]})"
      ]
     },
     "execution_count": 72,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "grid_search.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 73,
   "id": "a7c79885",
   "metadata": {},
   "outputs": [],
   "source": [
    "ypred2 = grid_search.predict(X_test) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "id": "1a0c8e98",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "R2 Score: 0.6191253137183562\n",
      "Mean Squared Error: 0.3935585312540244\n",
      "Mean Absolute Error: 0.46626575044290997\n"
     ]
    }
   ],
   "source": [
    "print('R2 Score: ' + str(r2_score(y_test, ypred2)))\n",
    "print('Mean Squared Error: ' + str(mean_squared_error(y_test, ypred2)))\n",
    "print('Mean Absolute Error: ' + str(mean_absolute_error(y_test, ypred2)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "id": "af0f5796",
   "metadata": {},
   "outputs": [],
   "source": [
    "rm = Ridge()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 96,
   "id": "3475b01b",
   "metadata": {},
   "outputs": [],
   "source": [
    "grid_search3 = GridSearchCV(rm, param_grid={'copy_X': [True,False], 'fit_intercept': [True, False], 'alpha':[1, 10, 25, 50, 100], 'solver':['svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga', 'lbfgs']},  cv=5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 97,
   "id": "2d0c68ea",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 762, in fit\n",
      "    return super().fit(X, y, sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 593, in fit\n",
      "    self.coef_, self.n_iter_ = _ridge_regression(\n",
      "  File \"C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_ridge.py\", line 397, in _ridge_regression\n",
      "    raise ValueError(\"Known solvers are 'sparse_cg', 'cholesky', 'svd'\"\n",
      "ValueError: Known solvers are 'sparse_cg', 'cholesky', 'svd' 'lsqr', 'sag' or 'saga'. Got lbfgs.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\ituser\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_search.py:922: UserWarning: One or more of the test scores are non-finite: [-1.37456437 -1.37456437 -1.3745091  -1.37480513 -1.23216688 -1.09120892\n",
      "         nan -1.04128222 -1.04128222 -1.0412226  -1.04149176 -0.92809009\n",
      " -0.81957868         nan -1.37456437 -1.37456437 -1.3745091  -1.37480513\n",
      " -1.23036142 -1.09076161         nan -1.04128222 -1.04128222 -1.0412226\n",
      " -1.04149176 -0.93136102 -0.82104658         nan  0.48060986  0.48060986\n",
      "  0.48072703  0.48041136  0.48633764  0.49395928         nan  0.49224189\n",
      "  0.49224189  0.49227948  0.49205331  0.49753446  0.50472804         nan\n",
      "  0.48060986  0.48060986  0.48072703  0.48041136  0.48572293  0.49375756\n",
      "         nan  0.49224189  0.49224189  0.49227948  0.49205331  0.49746502\n",
      "  0.5046689          nan  0.5890081   0.5890081   0.60436442  0.58902934\n",
      "  0.58892246  0.59100895         nan  0.59126152  0.59126152  0.60576334\n",
      "  0.59128391  0.59166351  0.59301916         nan  0.5890081   0.5890081\n",
      "  0.60436442  0.58902934  0.58924397  0.5909661          nan  0.59126152\n",
      "  0.59126152  0.60576334  0.59128391  0.59167998  0.59293021         nan\n",
      "  0.60381376  0.60381376  0.60907416  0.60612607  0.60341915  0.60330961\n",
      "         nan  0.60456904  0.60456904  0.60949553  0.60677699  0.60408944\n",
      "  0.60414861         nan  0.60381376  0.60381376  0.60907416  0.60612607\n",
      "  0.60332081  0.60331107         nan  0.60456904  0.60456904  0.60949553\n",
      "  0.60677699  0.60408963  0.60411798         nan  0.59300456  0.59300456\n",
      "  0.59373841  0.59373841  0.59248613  0.59175064         nan  0.59329816\n",
      "  0.59329816  0.59398224  0.59398224  0.5927774   0.59193143         nan\n",
      "  0.59300456  0.59300456  0.59373841  0.59373841  0.59250436  0.59174884\n",
      "         nan  0.59329816  0.59329816  0.59398224  0.59398224  0.59278362\n",
      "  0.59204953         nan]\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "grid_search3.fit(X_train, y_train)\n",
    "ypred3 = grid_search3.predict(X_test) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 98,
   "id": "d12d3d17",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "R2 Score: 0.6191253137183562\n",
      "Mean Squared Error: 0.3935585312540244\n",
      "Mean Absolute Error: 0.46626575044290997\n"
     ]
    }
   ],
   "source": [
    "print('R2 Score: ' + str(r2_score(y_test, ypred2)))\n",
    "print('Mean Squared Error: ' + str(mean_squared_error(y_test, ypred2)))\n",
    "print('Mean Absolute Error: ' + str(mean_absolute_error(y_test, ypred2)))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bfde850d",
   "metadata": {},
   "source": [
    "After cross validation and a bit of parameter tuning including using the ridge object to also tune the alpha parameter for regularization, the R2 score is now 0.6191."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bd1214f2",
   "metadata": {},
   "source": [
    "This is a pretty good baseline performance considering it is significantly higher than 0.5. In the next Notebook, we will look at other ways to predict CPI."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "id": "87a6c1b8",
   "metadata": {},
   "outputs": [],
   "source": [
    "scale_df.to_csv('ScaledData')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "89d3ebe3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
